In [ ]:
import pandas as pd
import matplotlib as pyplot
import numpy as np
import seaborn as sns
data=pd.read_csv("car_evaluation.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buy_price     1728 non-null object
maint_cost    1728 non-null object
doors         1728 non-null object
person        1728 non-null object
boot_space    1728 non-null object
safety        1728 non-null object
class         1728 non-null object
dtypes: object(7)
memory usage: 94.6+ KB


In [ ]:
data.head(10)

buy_price maint_cost doors person boot_space safety  class
0     vhigh      vhigh     2      2      small    low  unacc
1     vhigh      vhigh     2      2      small    med  unacc
2     vhigh      vhigh     2      2      small   high  unacc
3     vhigh      vhigh     2      2        med    low  unacc
4     vhigh      vhigh     2      2        med    med  unacc
5     vhigh      vhigh     2      2        med   high  unacc
6     vhigh      vhigh     2      2        big    low  unacc
7     vhigh      vhigh     2      2        big    med  unacc
8     vhigh      vhigh     2      2        big   high  unacc
9     vhigh      vhigh     2      4      small    low  unacc

In [ ]:
rows,cols=data.shape
print("rows:",rows)
print("columns:",cols)

rows: 1728
columns: 7


In [ ]:
data['class'].value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: class, dtype: int64

In [ ]:
data['doors'].max()


'5more'

In [ ]:
data['person'].max()


'more'

In [ ]:
data['doors'].min()


'2'

In [ ]:
data['person'].min()

'2'

In [ ]:
data.isna().sum()

buy_price     0
maint_cost    0
doors         0
person        0
boot_space    0
safety        0
class         0
dtype: int64

In [ ]:
#except the target function to be encoded

from sklearn.preprocessing import LabelEncoder,StandardScaler
for col in data.columns[:-1]:
    le =LabelEncoder()
    data[col]=le.fit_transform(data[col])

In [ ]:
print(data['doors'].max())

print(data['doors'].min())

3
0


In [ ]:
print(data['person'].max())

print(data['person'].min())

2
0


In [ ]:
data.columns

Index(['buy_price', 'maint_cost', 'doors', 'person', 'boot_space', 'safety',
       'class'],
      dtype='object')

In [ ]:
X = data[['buy_price', 'maint_cost', 'doors', 'person', 'boot_space', 'safety']]
y = data[['class']]

In [ ]:
#spliting the dataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = .30,random_state=42)

In [ ]:
y sc = StandardScaler()
X_train = sc.fit_transform(X_train) by
X_test = sc.fit_transform(X_test)

In [ ]:
x_=data.iloc[:,:-1]
y_=data.iloc[:,:-1]
print(x_)
print(y_)

      buy_price  maint_cost  doors  person  boot_space  safety
0             3           3      0       0           2       1
1             3           3      0       0           2       2
2             3           3      0       0           2       0
3             3           3      0       0           1       1
4             3           3      0       0           1       2
...         ...         ...    ...     ...         ...     ...
1723          1           1      3       2           1       2
1724          1           1      3       2           1       0
1725          1           1      3       2           0       1
1726          1           1      3       2           0       2
1727          1           1      3       2           0       0

[1728 rows x 6 columns]
      buy_price  maint_cost  doors  person  boot_space  safety
0             3           3      0       0           2       1
1             3           3      0       0           2       2
2             3           3   

In [ ]:
#perform PCA with diffrent number of component
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

best_accuracy=0
best_n_components=0

for n_components in range(2,6):
    pca=PCA(n_components=n_components)
    X_train_pca=pca.fit_transform(X_train)
    X_test_pca=pca.transform(X_test)

    #train a classifier (Random Forest classifier)
    clf=RandomForestClassifier(random_state=42)
    clf.fit(X_train_pca,y_train)

    #testing the data set
    y_pred = clf.predict(X_test_pca)
    accuracy=accuracy_score(y_test,y_pred)
    print(f"no:of PCA component: {n_components},Accuracy{accuracy}")
    #update the best accuracy and number of components
    if accuracy > best_accuracy:
        best_accuracy=accuracy
        best_n_components=n_components

print(f"best no:of PCA accuarcy:{best_n_components}, Accuracy{best_accuracy}")



/tmp/ipykernel_3293/3719750816.py:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train_pca,y_train)
/tmp/ipykernel_3293/3719750816.py:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train_pca,y_train)


no:of PCA component: 2,Accuracy0.6184971098265896
no:of PCA component: 3,Accuracy0.6396917148362236


/tmp/ipykernel_3293/3719750816.py:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train_pca,y_train)
/tmp/ipykernel_3293/3719750816.py:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train_pca,y_train)


no:of PCA component: 4,Accuracy0.7745664739884393
no:of PCA component: 5,Accuracy0.7649325626204239
best no:of PCA accuarcy:4, Accuracy0.7745664739884393


In [ ]:
#calculate the covariance  matrix
cov_mat = np.cov(X_train.T)
print("covariance  matrix")
print(cov_mat)

covariance  matrix
[[ 1.00082781 -0.0018546  -0.01020328  0.01780223 -0.02847234  0.00383472]
 [-0.0018546   1.00082781 -0.02866354 -0.00412951  0.0112374   0.00732274]
 [-0.01020328 -0.02866354  1.00082781 -0.00492403 -0.0173827  -0.01289684]
 [ 0.01780223 -0.00412951 -0.00492403  1.00082781  0.01368608  0.02020217]
 [-0.02847234  0.0112374  -0.0173827   0.01368608  1.00082781 -0.00609855]
 [ 0.00383472  0.00732274 -0.01289684  0.02020217 -0.00609855  1.00082781]]
